"""Cinema slug resolution, the settings file, and defaults."""

import json

import pytest
from conftest import load

from pathe import config

KNOWN = [c["slug"] for c in load("cinemas.json")]


def test_default_set_is_the_four_in_reach(monkeypatch):
    monkeypatch.delenv("PATHE_CINEMAS", raising=False)
    assert config.default_cinemas() == [
        "pathe-helmond",
        "pathe-eindhoven",
        "pathe-tilburg-centrum",
        "pathe-tilburg-stappegoor",
    ]


def test_env_overrides_the_default(monkeypatch):
    monkeypatch.setenv("PATHE_CINEMAS", "pathe-breda, pathe-delft")
    assert config.default_cinemas() == ["pathe-breda", "pathe-delft"]


def test_blank_env_falls_back(monkeypatch):
    monkeypatch.setenv("PATHE_CINEMAS", "   ")
    assert config.default_cinemas() == config.DEFAULT_CINEMAS


def test_exact_slug_resolves():
    got, unknown = config.resolve(["pathe-helmond"], KNOWN)
    assert got == ["pathe-helmond"] and unknown == []


def test_short_name_gains_the_prefix():
    got, _ = config.resolve(["helmond", "eindhoven"], KNOWN)
    assert got == ["pathe-helmond", "pathe-eindhoven"]


def test_case_and_spaces_tolerated():
    got, _ = config.resolve(["  Helmond ", "Tilburg Centrum"], KNOWN)
    assert got == ["pathe-helmond", "pathe-tilburg-centrum"]


def test_unprefixed_cinema_still_resolves():
    """Tuschinski has no `pathe-` prefix, which is why resolution runs against
    the real slug list instead of doing string surgery."""
    got, unknown = config.resolve(["tuschinski"], KNOWN)
    assert got == ["koninklijk-theater-tuschinski"] and unknown == []


def test_ambiguous_substring_is_reported_not_guessed():
    got, unknown = config.resolve(["tilburg"], KNOWN)
    assert got == [] and unknown == ["tilburg"]


def test_unknown_is_reported():
    got, unknown = config.resolve(["atlantis"], KNOWN)
    assert got == [] and unknown == ["atlantis"]


def test_duplicates_collapse():
    got, _ = config.resolve(["helmond", "pathe-helmond"], KNOWN)
    assert got == ["pathe-helmond"]


def test_blank_entries_ignored():
    got, unknown = config.resolve(["helmond", "", "  "], KNOWN)
    assert got == ["pathe-helmond"] and unknown == []


def test_error_type_is_shared_between_api_and_errors():
    """`config` raises PatheError without importing the HTTP client, so the
    type has to live somewhere both modules can reach."""
    from pathe import api, errors

    assert api.PatheError is errors.PatheError


def test_suite_does_not_read_the_real_home_config():
    """The autouse fixture in conftest points XDG_CONFIG_HOME at a tmp dir, so
    a settings.json on the developer's machine cannot change test outcomes."""
    import os
    from pathlib import Path

    assert Path(os.environ["XDG_CONFIG_HOME"]) != Path.home() / ".config"


def write_settings(payload):
    """Write a settings.json into the tmp XDG_CONFIG_HOME the autouse fixture
    set up, and return its path."""
    import os
    from pathlib import Path

    path = Path(os.environ["XDG_CONFIG_HOME"]) / "pathe" / "settings.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(payload if isinstance(payload, str) else json.dumps(payload))
    return path


def test_settings_path_follows_xdg():
    import os
    from pathlib import Path

    assert config.settings_path() == (
        Path(os.environ["XDG_CONFIG_HOME"]) / "pathe" / "settings.json"
    )


def test_missing_settings_file_is_not_an_error():
    assert config.load_settings() == {}


def test_favorites_default_to_the_built_in_four():
    assert config.favorites() == config.DEFAULT_CINEMAS


def test_favorites_come_from_the_file():
    write_settings({"favorites": ["pathe-breda", "pathe-delft"]})
    assert config.favorites() == ["pathe-breda", "pathe-delft"]


def test_unknown_keys_in_the_file_are_ignored():
    write_settings({"favorites": ["pathe-breda"], "kleur": "paars"})
    assert config.favorites() == ["pathe-breda"]


def test_empty_favorites_list_falls_back():
    write_settings({"favorites": []})
    assert config.favorites() == config.DEFAULT_CINEMAS


def test_malformed_json_is_fatal():
    """The file is machine-generated by Nix; a broken one is a bug to surface,
    not something to quietly fall back from."""
    from pathe.errors import PatheError

    path = write_settings("{ dit is geen json")
    with pytest.raises(PatheError, match=str(path)):
        config.load_settings()


def test_non_object_json_is_fatal():
    from pathe.errors import PatheError

    write_settings("[1, 2, 3]")
    with pytest.raises(PatheError, match="JSON-object"):
        config.load_settings()


def test_favorites_of_the_wrong_type_is_fatal():
    from pathe.errors import PatheError

    write_settings({"favorites": "pathe-breda"})
    with pytest.raises(PatheError, match="lijst strings"):
        config.favorites()


def test_env_wins_over_the_file(monkeypatch):
    """settings.json is declarative and permanent; PATHE_CINEMAS is the ad-hoc
    override for one shell, so it is the more specific signal."""
    write_settings({"favorites": ["pathe-breda"]})
    monkeypatch.setenv("PATHE_CINEMAS", "pathe-delft")
    assert config.default_cinemas() == ["pathe-delft"]


def test_favorites_ignore_the_env(monkeypatch):
    """`-f` means *my* cinemas, whatever this shell says."""
    write_settings({"favorites": ["pathe-breda"]})
    monkeypatch.setenv("PATHE_CINEMAS", "pathe-delft")
    assert config.favorites() == ["pathe-breda"]


def test_default_falls_through_the_file_when_env_is_unset():
    write_settings({"favorites": ["pathe-breda"]})
    assert config.default_cinemas() == ["pathe-breda"]
