"""Defaults, overridable from a settings file and from the environment.

Precedence, most specific first:

    -c <slugs>  >  PATHE_CINEMAS  >  settings.json favorites  >  DEFAULT_CINEMAS

The env var beats the file because the file is declarative and permanent --
written by a home-manager module -- while PATHE_CINEMAS is the ad-hoc override
for a single shell.
"""

import json
import os
from pathlib import Path

from .errors import PatheError

# The four cinemas actually in reach. Everything defaults to these rather than
# to all 31: a national sweep is ~1000 requests and answers a question nobody
# asked. `pathe where` is the cheap way to ask a national question.
DEFAULT_CINEMAS = [
    "pathe-helmond",
    "pathe-eindhoven",
    "pathe-tilburg-centrum",
    "pathe-tilburg-stappegoor",
]

# Pathé publishes ~10 months out, but that tail is almost entirely opera and
# ballet encores. Two months covers the real programme; `--days` widens it when
# you are chasing something like an André Rieu date.
DEFAULT_HORIZON_DAYS = 60


def settings_path():
    root = os.environ.get("XDG_CONFIG_HOME", "").strip()
    base = Path(root) if root else Path.home() / ".config"
    return base / "pathe" / "settings.json"


def load_settings():
    """The parsed settings file, or `{}` when there is none.

    A file that exists but does not parse raises: it is generated by Nix, so a
    broken one means the config is wrong and should say so rather than silently
    reverting to the built-in defaults.
    """
    path = settings_path()
    try:
        raw = path.read_text()
    except FileNotFoundError:
        return {}
    except OSError as exc:
        raise PatheError(f"{path}: {exc}") from exc
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise PatheError(f"{path}: geen geldige JSON ({exc})") from exc
    if not isinstance(parsed, dict):
        raise PatheError(f"{path}: verwacht een JSON-object")
    return parsed


def favorites():
    """The configured cinemas, or the built-in four.

    Deliberately ignores PATHE_CINEMAS: `-f` means *my* cinemas, whatever the
    current shell has been told.
    """
    configured = load_settings().get("favorites")
    if configured is None:
        return list(DEFAULT_CINEMAS)
    if not isinstance(configured, list) or not all(isinstance(s, str) for s in configured):
        raise PatheError(f"{settings_path()}: `favorites` moet een lijst strings zijn")
    kept = [s.strip() for s in configured if s.strip()]
    return kept or list(DEFAULT_CINEMAS)


def default_cinemas():
    raw = os.environ.get("PATHE_CINEMAS", "").strip()
    if not raw:
        return favorites()
    return [s.strip() for s in raw.split(",") if s.strip()]


def resolve(requested, known_slugs):
    """Map what the user typed onto real cinema slugs.

    Resolved against the live list rather than by string surgery, because the
    prefix is not universal -- `pathe-helmond` has it, `koninklijk-theater-
    tuschinski` does not -- so guessing gets Tuschinski wrong. Accepts the exact
    slug, the slug without `pathe-`, or a unique case-insensitive substring.
    """
    known = list(known_slugs)
    out, unknown = [], []
    for raw in requested:
        needle = raw.strip().lower().replace(" ", "-")
        if not needle:
            continue
        if needle in known:
            out.append(needle)
            continue
        if f"pathe-{needle}" in known:
            out.append(f"pathe-{needle}")
            continue
        hits = [s for s in known if needle in s]
        if len(hits) == 1:
            out.append(hits[0])
        else:
            unknown.append(raw)
    return list(dict.fromkeys(out)), unknown
